### ISSUE TITLE
[PE-D][Tester B] [Undo] NullPointerException executing undo after deletecustomer command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-4/tp#120]
Command:
```
deletecustomer 1
undo
```

UI output:

![image.png](https://raw.githubusercontent.com/c0j0s/ped/main/files/79de5387-3aab-4d45-9575-c73cef390b64.png)

Stacktrace:
```
Result: Undo success!
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at seedu.address.ui.ServiceCard.<init>(ServiceCard.java:74)
        at seedu.address.ui.ServiceListPanel$ServiceListViewCell.updateItem(ServiceListPanel.java:48)
        at seedu.address.ui.ServiceListPanel$ServiceListViewCell.updateItem(ServiceListPanel.java:39)
        at javafx.scene.control.ListCell.updateItem(ListCell.java:478)
        at javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
        at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1708)
        at javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1947)
        at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1250)
        at javafx.scene.Parent.layout(Parent.java:1204)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at seedu.address.ui.VehicleCard.<init>(VehicleCard.java:70)
        at seedu.address.ui.VehicleListPanel$VehicleListViewCell.updateItem(VehicleListPanel.java:48)
        at seedu.address.ui.VehicleListPanel$VehicleListViewCell.updateItem(VehicleListPanel.java:39)
        at javafx.scene.control.ListCell.updateItem(ListCell.java:478)
        at javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
        at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1708)
        at javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1947)
        at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1250)
        at javafx.scene.Parent.layout(Parent.java:1204)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
````

This issue affects `listcustomers`, `listvehicles` and `listservices` commands too as they can no longer display any items in the UI.

`redo` is also affected.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: c0j0s/ped#1

**Comment by kimberlybp** [comment]
This is a GUI issue but i probably need to run through how undo/redo features work with you first haha im not sure how it works rn tbh @junlee1991
